// Code generated by protoc-gen-go. DO NOT EDIT.
// source: grpc.proto

/*
Package grpc is a generated protocol buffer package.

It is generated from these files:
	grpc.proto

It has these top-level messages:
	Task
	TaskList
	Void
	HelloRequest
	HelloReply
	Point
	Rectangle
	Feature
	RouteNote
	RouteSummary
	Err
*/
package grpc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc1 "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Task struct {
	Text string `protobuf:"bytes,1,opt,name=text" json:"text,omitempty"`
	Done bool   `protobuf:"varint,2,opt,name=done" json:"done,omitempty"`
}

func (m *Task) Reset()                    { *m = Task{} }
func (m *Task) String() string            { return proto.CompactTextString(m) }
func (*Task) ProtoMessage()               {}
func (*Task) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Task) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *Task) GetDone() bool {
	if m != nil {
		return m.Done
	}
	return false
}

type TaskList struct {
	Tasks []*Task `protobuf:"bytes,1,rep,name=tasks" json:"tasks,omitempty"`
}

func (m *TaskList) Reset()                    { *m = TaskList{} }
func (m *TaskList) String() string            { return proto.CompactTextString(m) }
func (*TaskList) ProtoMessage()               {}
func (*TaskList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *TaskList) GetTasks() []*Task {
	if m != nil {
		return m.Tasks
	}
	return nil
}

type Void struct {
}

func (m *Void) Reset()                    { *m = Void{} }
func (m *Void) String() string            { return proto.CompactTextString(m) }
func (*Void) ProtoMessage()               {}
func (*Void) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type HelloRequest struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *HelloRequest) Reset()                    { *m = HelloRequest{} }
func (m *HelloRequest) String() string            { return proto.CompactTextString(m) }
func (*HelloRequest) ProtoMessage()               {}
func (*HelloRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *HelloRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type HelloReply struct {
	Message string `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
}

func (m *HelloReply) Reset()                    { *m = HelloReply{} }
func (m *HelloReply) String() string            { return proto.CompactTextString(m) }
func (*HelloReply) ProtoMessage()               {}
func (*HelloReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *HelloReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type Point struct {
	Latitude  int32 `protobuf:"varint,1,opt,name=latitude" json:"latitude,omitempty"`
	Longitude int32 `protobuf:"varint,2,opt,name=longitude" json:"longitude,omitempty"`
}

func (m *Point) Reset()                    { *m = Point{} }
func (m *Point) String() string            { return proto.CompactTextString(m) }
func (*Point) ProtoMessage()               {}
func (*Point) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *Point) GetLatitude() int32 {
	if m != nil {
		return m.Latitude
	}
	return 0
}

func (m *Point) GetLongitude() int32 {
	if m != nil {
		return m.Longitude
	}
	return 0
}

type Rectangle struct {
	Lo *Point `protobuf:"bytes,1,opt,name=lo" json:"lo,omitempty"`
	Hi *Point `protobuf:"bytes,2,opt,name=hi" json:"hi,omitempty"`
}

func (m *Rectangle) Reset()                    { *m = Rectangle{} }
func (m *Rectangle) String() string            { return proto.CompactTextString(m) }
func (*Rectangle) ProtoMessage()               {}
func (*Rectangle) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *Rectangle) GetLo() *Point {
	if m != nil {
		return m.Lo
	}
	return nil
}

func (m *Rectangle) GetHi() *Point {
	if m != nil {
		return m.Hi
	}
	return nil
}

type Feature struct {
	Name     string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Location *Point `protobuf:"bytes,2,opt,name=location" json:"location,omitempty"`
}

func (m *Feature) Reset()                    { *m = Feature{} }
func (m *Feature) String() string            { return proto.CompactTextString(m) }
func (*Feature) ProtoMessage()               {}
func (*Feature) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *Feature) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Feature) GetLocation() *Point {
	if m != nil {
		return m.Location
	}
	return nil
}

type RouteNote struct {
	Location *Point `protobuf:"bytes,1,opt,name=location" json:"location,omitempty"`
	Message  string `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
}

func (m *RouteNote) Reset()                    { *m = RouteNote{} }
func (m *RouteNote) String() string            { return proto.CompactTextString(m) }
func (*RouteNote) ProtoMessage()               {}
func (*RouteNote) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *RouteNote) GetLocation() *Point {
	if m != nil {
		return m.Location
	}
	return nil
}

func (m *RouteNote) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type RouteSummary struct {
	PointCount   int32 `protobuf:"varint,1,opt,name=point_count,json=pointCount" json:"point_count,omitempty"`
	FeatureCount int32 `protobuf:"varint,2,opt,name=feature_count,json=featureCount" json:"feature_count,omitempty"`
	Distance     int32 `protobuf:"varint,3,opt,name=distance" json:"distance,omitempty"`
	ElapsedTime  int32 `protobuf:"varint,4,opt,name=elapsed_time,json=elapsedTime" json:"elapsed_time,omitempty"`
}

func (m *RouteSummary) Reset()                    { *m = RouteSummary{} }
func (m *RouteSummary) String() string            { return proto.CompactTextString(m) }
func (*RouteSummary) ProtoMessage()               {}
func (*RouteSummary) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *RouteSummary) GetPointCount() int32 {
	if m != nil {
		return m.PointCount
	}
	return 0
}

func (m *RouteSummary) GetFeatureCount() int32 {
	if m != nil {
		return m.FeatureCount
	}
	return 0
}

func (m *RouteSummary) GetDistance() int32 {
	if m != nil {
		return m.Distance
	}
	return 0
}

func (m *RouteSummary) GetElapsedTime() int32 {
	if m != nil {
		return m.ElapsedTime
	}
	return 0
}

type Err struct {
	Msg string `protobuf:"bytes,1,opt,name=Msg" json:"Msg,omitempty"`
}

func (m *Err) Reset()                    { *m = Err{} }
func (m *Err) String() string            { return proto.CompactTextString(m) }
func (*Err) ProtoMessage()               {}
func (*Err) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *Err) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func init() {
	proto.RegisterType((*Task)(nil), "grpc.Task")
	proto.RegisterType((*TaskList)(nil), "grpc.TaskList")
	proto.RegisterType((*Void)(nil), "grpc.Void")
	proto.RegisterType((*HelloRequest)(nil), "grpc.HelloRequest")
	proto.RegisterType((*HelloReply)(nil), "grpc.HelloReply")
	proto.RegisterType((*Point)(nil), "grpc.Point")
	proto.RegisterType((*Rectangle)(nil), "grpc.Rectangle")
	proto.RegisterType((*Feature)(nil), "grpc.Feature")
	proto.RegisterType((*RouteNote)(nil), "grpc.RouteNote")
	proto.RegisterType((*RouteSummary)(nil), "grpc.RouteSummary")
	proto.RegisterType((*Err)(nil), "grpc.Err")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc1.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc1.SupportPackageIsVersion4

// Client API for Todo service

type TodoClient interface {
	List(ctx context.Context, in *Void, opts ...grpc1.CallOption) (*TaskList, error)
	Add(ctx context.Context, in *Task, opts ...grpc1.CallOption) (*Void, error)
}

type todoClient struct {
	cc *grpc1.ClientConn
}

func NewTodoClient(cc *grpc1.ClientConn) TodoClient {
	return &todoClient{cc}
}

func (c *todoClient) List(ctx context.Context, in *Void, opts ...grpc1.CallOption) (*TaskList, error) {
	out := new(TaskList)
	err := grpc1.Invoke(ctx, "/grpc.Todo/List", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *todoClient) Add(ctx context.Context, in *Task, opts ...grpc1.CallOption) (*Void, error) {
	out := new(Void)
	err := grpc1.Invoke(ctx, "/grpc.Todo/Add", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Todo service

type TodoServer interface {
	List(context.Context, *Void) (*TaskList, error)
	Add(context.Context, *Task) (*Void, error)
}

func RegisterTodoServer(s *grpc1.Server, srv TodoServer) {
	s.RegisterService(&_Todo_serviceDesc, srv)
}

func _Todo_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc1.UnaryServerInterceptor) (interface{}, error) {
	in := new(Void)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TodoServer).List(ctx, in)
	}
	info := &grpc1.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.Todo/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TodoServer).List(ctx, req.(*Void))
	}
	return interceptor(ctx, in, info, handler)
}

func _Todo_Add_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc1.UnaryServerInterceptor) (interface{}, error) {
	in := new(Task)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TodoServer).Add(ctx, in)
	}
	info := &grpc1.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.Todo/Add",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TodoServer).Add(ctx, req.(*Task))
	}
	return interceptor(ctx, in, info, handler)
}

var _Todo_serviceDesc = grpc1.ServiceDesc{
	ServiceName: "grpc.Todo",
	HandlerType: (*TodoServer)(nil),
	Methods: []grpc1.MethodDesc{
		{
			MethodName: "List",
			Handler:    _Todo_List_Handler,
		},
		{
			MethodName: "Add",
			Handler:    _Todo_Add_Handler,
		},
	},
	Streams:  []grpc1.StreamDesc{},
	Metadata: "grpc.proto",
}

// Client API for Greeter service

type GreeterClient interface {
	SayHello(ctx context.Context, in *HelloRequest, opts ...grpc1.CallOption) (*HelloReply, error)
}

type greeterClient struct {
	cc *grpc1.ClientConn
}

func NewGreeterClient(cc *grpc1.ClientConn) GreeterClient {
	return &greeterClient{cc}
}

func (c *greeterClient) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc1.CallOption) (*HelloReply, error) {
	out := new(HelloReply)
	err := grpc1.Invoke(ctx, "/grpc.Greeter/SayHello", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Greeter service

type GreeterServer interface {
	SayHello(context.Context, *HelloRequest) (*HelloReply, error)
}

func RegisterGreeterServer(s *grpc1.Server, srv GreeterServer) {
	s.RegisterService(&_Greeter_serviceDesc, srv)
}

func _Greeter_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc1.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).SayHello(ctx, in)
	}
	info := &grpc1.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.Greeter/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).SayHello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Greeter_serviceDesc = grpc1.ServiceDesc{
	ServiceName: "grpc.Greeter",
	HandlerType: (*GreeterServer)(nil),
	Methods: []grpc1.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _Greeter_SayHello_Handler,
		},
	},
	Streams:  []grpc1.StreamDesc{},
	Metadata: "grpc.proto",
}

// Client API for RouteGuide service

type RouteGuideClient interface {
	GetFeature(ctx context.Context, in *Point, opts ...grpc1.CallOption) (*Feature, error)
	ListFeatures(ctx context.Context, in *Rectangle, opts ...grpc1.CallOption) (RouteGuide_ListFeaturesClient, error)
	RecordRoute(ctx context.Context, opts ...grpc1.CallOption) (RouteGuide_RecordRouteClient, error)
	RouteChat(ctx context.Context, opts ...grpc1.CallOption) (RouteGuide_RouteChatClient, error)
}

type routeGuideClient struct {
	cc *grpc1.ClientConn
}

func NewRouteGuideClient(cc *grpc1.ClientConn) RouteGuideClient {
	return &routeGuideClient{cc}
}

func (c *routeGuideClient) GetFeature(ctx context.Context, in *Point, opts ...grpc1.CallOption) (*Feature, error) {
	out := new(Feature)
	err := grpc1.Invoke(ctx, "/grpc.RouteGuide/GetFeature", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routeGuideClient) ListFeatures(ctx context.Context, in *Rectangle, opts ...grpc1.CallOption) (RouteGuide_ListFeaturesClient, error) {
	stream, err := grpc1.NewClientStream(ctx, &_RouteGuide_serviceDesc.Streams[0], c.cc, "/grpc.RouteGuide/ListFeatures", opts...)
	if err != nil {
		return nil, err
	}
	x := &routeGuideListFeaturesClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type RouteGuide_ListFeaturesClient interface {
	Recv() (*Feature, error)
	grpc1.ClientStream
}

type routeGuideListFeaturesClient struct {
	grpc1.ClientStream
}

func (x *routeGuideListFeaturesClient) Recv() (*Feature, error) {
	m := new(Feature)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *routeGuideClient) RecordRoute(ctx context.Context, opts ...grpc1.CallOption) (RouteGuide_RecordRouteClient, error) {
	stream, err := grpc1.NewClientStream(ctx, &_RouteGuide_serviceDesc.Streams[1], c.cc, "/grpc.RouteGuide/RecordRoute", opts...)
	if err != nil {
		return nil, err
	}
	x := &routeGuideRecordRouteClient{stream}
	return x, nil
}

type RouteGuide_RecordRouteClient interface {
	Send(*Point) error
	CloseAndRecv() (*RouteSummary, error)
	grpc1.ClientStream
}

type routeGuideRecordRouteClient struct {
	grpc1.ClientStream
}

func (x *routeGuideRecordRouteClient) Send(m *Point) error {
	return x.ClientStream.SendMsg(m)
}

func (x *routeGuideRecordRouteClient) CloseAndRecv() (*RouteSummary, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(RouteSummary)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *routeGuideClient) RouteChat(ctx context.Context, opts ...grpc1.CallOption) (RouteGuide_RouteChatClient, error) {
	stream, err := grpc1.NewClientStream(ctx, &_RouteGuide_serviceDesc.Streams[2], c.cc, "/grpc.RouteGuide/RouteChat", opts...)
	if err != nil {
		return nil, err
	}
	x := &routeGuideRouteChatClient{stream}
	return x, nil
}

type RouteGuide_RouteChatClient interface {
	Send(*RouteNote) error
	Recv() (*RouteNote, error)
	grpc1.ClientStream
}

type routeGuideRouteChatClient struct {
	grpc1.ClientStream
}

func (x *routeGuideRouteChatClient) Send(m *RouteNote) error {
	return x.ClientStream.SendMsg(m)
}

func (x *routeGuideRouteChatClient) Recv() (*RouteNote, error) {
	m := new(RouteNote)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for RouteGuide service

type RouteGuideServer interface {
	GetFeature(context.Context, *Point) (*Feature, error)
	ListFeatures(*Rectangle, RouteGuide_ListFeaturesServer) error
	RecordRoute(RouteGuide_RecordRouteServer) error
	RouteChat(RouteGuide_RouteChatServer) error
}

func RegisterRouteGuideServer(s *grpc1.Server, srv RouteGuideServer) {
	s.RegisterService(&_RouteGuide_serviceDesc, srv)
}

func _RouteGuide_GetFeature_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc1.UnaryServerInterceptor) (interface{}, error) {
	in := new(Point)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouteGuideServer).GetFeature(ctx, in)
	}
	info := &grpc1.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.RouteGuide/GetFeature",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouteGuideServer).GetFeature(ctx, req.(*Point))
	}
	return interceptor(ctx, in, info, handler)
}

func _RouteGuide_ListFeatures_Handler(srv interface{}, stream grpc1.ServerStream) error {
	m := new(Rectangle)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RouteGuideServer).ListFeatures(m, &routeGuideListFeaturesServer{stream})
}

type RouteGuide_ListFeaturesServer interface {
	Send(*Feature) error
	grpc1.ServerStream
}

type routeGuideListFeaturesServer struct {
	grpc1.ServerStream
}

func (x *routeGuideListFeaturesServer) Send(m *Feature) error {
	return x.ServerStream.SendMsg(m)
}

func _RouteGuide_RecordRoute_Handler(srv interface{}, stream grpc1.ServerStream) error {
	return srv.(RouteGuideServer).RecordRoute(&routeGuideRecordRouteServer{stream})
}

type RouteGuide_RecordRouteServer interface {
	SendAndClose(*RouteSummary) error
	Recv() (*Point, error)
	grpc1.ServerStream
}

type routeGuideRecordRouteServer struct {
	grpc1.ServerStream
}

func (x *routeGuideRecordRouteServer) SendAndClose(m *RouteSummary) error {
	return x.ServerStream.SendMsg(m)
}

func (x *routeGuideRecordRouteServer) Recv() (*Point, error) {
	m := new(Point)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _RouteGuide_RouteChat_Handler(srv interface{}, stream grpc1.ServerStream) error {
	return srv.(RouteGuideServer).RouteChat(&routeGuideRouteChatServer{stream})
}

type RouteGuide_RouteChatServer interface {
	Send(*RouteNote) error
	Recv() (*RouteNote, error)
	grpc1.ServerStream
}

type routeGuideRouteChatServer struct {
	grpc1.ServerStream
}

func (x *routeGuideRouteChatServer) Send(m *RouteNote) error {
	return x.ServerStream.SendMsg(m)
}

func (x *routeGuideRouteChatServer) Recv() (*RouteNote, error) {
	m := new(RouteNote)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _RouteGuide_serviceDesc = grpc1.ServiceDesc{
	ServiceName: "grpc.RouteGuide",
	HandlerType: (*RouteGuideServer)(nil),
	Methods: []grpc1.MethodDesc{
		{
			MethodName: "GetFeature",
			Handler:    _RouteGuide_GetFeature_Handler,
		},
	},
	Streams: []grpc1.StreamDesc{
		{
			StreamName:    "ListFeatures",
			Handler:       _RouteGuide_ListFeatures_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "RecordRoute",
			Handler:       _RouteGuide_RecordRoute_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "RouteChat",
			Handler:       _RouteGuide_RouteChat_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "grpc.proto",
}

// Client API for Tls service

type TlsClient interface {
	Test(ctx context.Context, in *Err, opts ...grpc1.CallOption) (*Err, error)
}

type tlsClient struct {
	cc *grpc1.ClientConn
}

func NewTlsClient(cc *grpc1.ClientConn) TlsClient {
	return &tlsClient{cc}
}

func (c *tlsClient) Test(ctx context.Context, in *Err, opts ...grpc1.CallOption) (*Err, error) {
	out := new(Err)
	err := grpc1.Invoke(ctx, "/grpc.Tls/Test", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Tls service

type TlsServer interface {
	Test(context.Context, *Err) (*Err, error)
}

func RegisterTlsServer(s *grpc1.Server, srv TlsServer) {
	s.RegisterService(&_Tls_serviceDesc, srv)
}

func _Tls_Test_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc1.UnaryServerInterceptor) (interface{}, error) {
	in := new(Err)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TlsServer).Test(ctx, in)
	}
	info := &grpc1.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.Tls/Test",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TlsServer).Test(ctx, req.(*Err))
	}
	return interceptor(ctx, in, info, handler)
}

var _Tls_serviceDesc = grpc1.ServiceDesc{
	ServiceName: "grpc.Tls",
	HandlerType: (*TlsServer)(nil),
	Methods: []grpc1.MethodDesc{
		{
			MethodName: "Test",
			Handler:    _Tls_Test_Handler,
		},
	},
	Streams:  []grpc1.StreamDesc{},
	Metadata: "grpc.proto",
}

func init() { proto.RegisterFile("grpc.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 579 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x54, 0x4f, 0x4f, 0xdb, 0x4e,
	0x10, 0x8d, 0x13, 0x03, 0xc9, 0x24, 0xfc, 0x7e, 0x68, 0x2e, 0x8d, 0x4c, 0x5b, 0xd2, 0xed, 0xbf,
	0xa8, 0xaa, 0x02, 0x32, 0xe7, 0x1e, 0x28, 0x02, 0x7a, 0x28, 0xa8, 0x32, 0x51, 0x0f, 0xbd, 0xa0,
	0xc5, 0x9e, 0x3a, 0x16, 0x6b, 0x6f, 0xba, 0xbb, 0x96, 0x9a, 0xcf, 0xd1, 0xcf, 0xd6, 0xef, 0x53,
	0xed, 0xae, 0x13, 0x12, 0x8a, 0x7a, 0x9b, 0x79, 0xef, 0xcd, 0xcc, 0xee, 0xec, 0xb3, 0x01, 0x72,
	0x35, 0x4f, 0x27, 0x73, 0x25, 0x8d, 0xc4, 0xd0, 0xc6, 0x6c, 0x02, 0xe1, 0x94, 0xeb, 0x3b, 0x44,
	0x08, 0x0d, 0xfd, 0x34, 0xc3, 0x60, 0x14, 0x8c, 0x7b, 0x89, 0x8b, 0x2d, 0x96, 0xc9, 0x8a, 0x86,
	0xed, 0x51, 0x30, 0xee, 0x26, 0x2e, 0x66, 0xef, 0xa1, 0x6b, 0xf5, 0x9f, 0x0b, 0x6d, 0x70, 0x04,
	0x5b, 0x86, 0xeb, 0x3b, 0x3d, 0x0c, 0x46, 0x9d, 0x71, 0x3f, 0x86, 0x89, 0xeb, 0x6e, 0xe9, 0xc4,
	0x13, 0x6c, 0x1b, 0xc2, 0xaf, 0xb2, 0xc8, 0x18, 0x83, 0xc1, 0x27, 0x12, 0x42, 0x26, 0xf4, 0xa3,
	0x26, 0xed, 0x3a, 0x57, 0xbc, 0xa4, 0xe5, 0x34, 0x1b, 0xb3, 0x37, 0x00, 0x8d, 0x66, 0x2e, 0x16,
	0x38, 0x84, 0x9d, 0x92, 0xb4, 0xe6, 0xf9, 0x52, 0xb4, 0x4c, 0xd9, 0x09, 0x6c, 0x7d, 0x91, 0x45,
	0x65, 0x30, 0x82, 0xae, 0xe0, 0xa6, 0x30, 0x75, 0xe6, 0x35, 0x5b, 0xc9, 0x2a, 0xc7, 0xa7, 0xd0,
	0x13, 0xb2, 0xca, 0x3d, 0xd9, 0x76, 0xe4, 0x3d, 0xc0, 0xce, 0xa0, 0x97, 0x50, 0x6a, 0x78, 0x95,
	0x0b, 0xc2, 0x7d, 0x68, 0x0b, 0xe9, 0x1a, 0xf4, 0xe3, 0xbe, 0xbf, 0x82, 0xeb, 0x9f, 0xb4, 0x85,
	0xb4, 0xe4, 0xac, 0x70, 0x0d, 0x1e, 0x92, 0xb3, 0x82, 0x9d, 0xc3, 0xce, 0x39, 0x71, 0x53, 0x2b,
	0x7a, 0xec, 0x42, 0xf8, 0x16, 0xba, 0x42, 0xa6, 0xdc, 0x14, 0xb2, 0x7a, 0xac, 0xc3, 0x8a, 0x64,
	0x57, 0xd0, 0x4b, 0x64, 0x6d, 0xe8, 0x4a, 0x9a, 0xcd, 0xaa, 0xe0, 0x1f, 0x55, 0xeb, 0x1b, 0x6a,
	0x6f, 0x6e, 0xe8, 0x57, 0x00, 0x03, 0xd7, 0xf0, 0xba, 0x2e, 0x4b, 0xae, 0x16, 0x78, 0x00, 0xfd,
	0xb9, 0xad, 0xbe, 0x49, 0x65, 0x5d, 0x99, 0x66, 0x59, 0xe0, 0xa0, 0x53, 0x8b, 0xe0, 0x4b, 0xd8,
	0xfd, 0xee, 0x6f, 0xd2, 0x48, 0xfc, 0xca, 0x06, 0x0d, 0xe8, 0x45, 0x11, 0x74, 0xb3, 0x42, 0x1b,
	0x5e, 0xa5, 0x34, 0xec, 0xf8, 0x7d, 0x2f, 0x73, 0x7c, 0x01, 0x03, 0x12, 0x7c, 0xae, 0x29, 0xbb,
	0x31, 0x45, 0x49, 0xc3, 0xd0, 0xf1, 0xfd, 0x06, 0x9b, 0x16, 0x25, 0xb1, 0x27, 0xd0, 0x39, 0x53,
	0x0a, 0xf7, 0xa0, 0x73, 0xa9, 0xf3, 0x66, 0x51, 0x36, 0x8c, 0x2f, 0x21, 0x9c, 0xca, 0x4c, 0xe2,
	0x2b, 0x08, 0x9d, 0xad, 0x1a, 0x1f, 0x59, 0xe3, 0x44, 0xff, 0xdd, 0x7b, 0xca, 0x72, 0xac, 0x85,
	0x07, 0xd0, 0x39, 0xc9, 0x32, 0x5c, 0x33, 0x5b, 0xb4, 0x56, 0xc0, 0x5a, 0xf1, 0x07, 0xd8, 0xb9,
	0x50, 0x44, 0x86, 0x14, 0xc6, 0xd0, 0xbd, 0xe6, 0x0b, 0xe7, 0x2a, 0x44, 0x2f, 0x5a, 0xb7, 0x61,
	0xb4, 0xb7, 0x81, 0xcd, 0xc5, 0x82, 0xb5, 0xe2, 0xdf, 0x01, 0x80, 0x5b, 0xde, 0x45, 0x5d, 0x64,
	0x84, 0xef, 0x00, 0x2e, 0xc8, 0x2c, 0x9f, 0x79, 0xfd, 0x29, 0xa2, 0x5d, 0x9f, 0x34, 0x1c, 0x6b,
	0x61, 0x0c, 0x03, 0x7b, 0xc8, 0x06, 0xd0, 0xf8, 0xbf, 0x17, 0xac, 0xac, 0xf6, 0x57, 0xc5, 0x51,
	0x80, 0x31, 0xf4, 0x13, 0x4a, 0xa5, 0xca, 0xdc, 0xcc, 0xcd, 0x01, 0xcd, 0x91, 0xd7, 0x9f, 0x92,
	0xb5, 0xc6, 0x01, 0x1e, 0x37, 0x7e, 0x39, 0x9d, 0x71, 0xb3, 0x1a, 0xb2, 0x34, 0x50, 0xf4, 0x10,
	0xb0, 0x25, 0x47, 0x41, 0xfc, 0x1a, 0x3a, 0x53, 0xa1, 0xf1, 0x39, 0x84, 0x53, 0xfb, 0x05, 0xf6,
	0xbc, 0xea, 0x4c, 0xa9, 0xe8, 0x3e, 0x64, 0xad, 0x8f, 0xcf, 0xbe, 0xed, 0xe7, 0x85, 0x99, 0xd5,
	0xb7, 0x93, 0x54, 0x96, 0x87, 0x39, 0x29, 0x93, 0xd6, 0x8b, 0x3b, 0xaa, 0xf4, 0xa1, 0x15, 0xdd,
	0x6e, 0xbb, 0x7f, 0xc7, 0xf1, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x66, 0xc3, 0x49, 0x1b, 0x49,
	0x04, 0x00, 0x00,
}
