// Code generated by protoc-gen-go. DO NOT EDIT.
// source: grpc.proto

/*
Package grpc is a generated protocol buffer package.

It is generated from these files:
	grpc.proto

It has these top-level messages:
	Task
	TaskList
	Void
	HelloRequest
	HelloReply
*/
package grpc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc1 "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Task struct {
	Text string `protobuf:"bytes,1,opt,name=text" json:"text,omitempty"`
	Done bool   `protobuf:"varint,2,opt,name=done" json:"done,omitempty"`
}

func (m *Task) Reset()                    { *m = Task{} }
func (m *Task) String() string            { return proto.CompactTextString(m) }
func (*Task) ProtoMessage()               {}
func (*Task) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Task) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *Task) GetDone() bool {
	if m != nil {
		return m.Done
	}
	return false
}

type TaskList struct {
	Tasks []*Task `protobuf:"bytes,1,rep,name=tasks" json:"tasks,omitempty"`
}

func (m *TaskList) Reset()                    { *m = TaskList{} }
func (m *TaskList) String() string            { return proto.CompactTextString(m) }
func (*TaskList) ProtoMessage()               {}
func (*TaskList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *TaskList) GetTasks() []*Task {
	if m != nil {
		return m.Tasks
	}
	return nil
}

type Void struct {
}

func (m *Void) Reset()                    { *m = Void{} }
func (m *Void) String() string            { return proto.CompactTextString(m) }
func (*Void) ProtoMessage()               {}
func (*Void) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type HelloRequest struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *HelloRequest) Reset()                    { *m = HelloRequest{} }
func (m *HelloRequest) String() string            { return proto.CompactTextString(m) }
func (*HelloRequest) ProtoMessage()               {}
func (*HelloRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *HelloRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type HelloReply struct {
	Message string `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
}

func (m *HelloReply) Reset()                    { *m = HelloReply{} }
func (m *HelloReply) String() string            { return proto.CompactTextString(m) }
func (*HelloReply) ProtoMessage()               {}
func (*HelloReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *HelloReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*Task)(nil), "grpc.Task")
	proto.RegisterType((*TaskList)(nil), "grpc.TaskList")
	proto.RegisterType((*Void)(nil), "grpc.Void")
	proto.RegisterType((*HelloRequest)(nil), "grpc.HelloRequest")
	proto.RegisterType((*HelloReply)(nil), "grpc.HelloReply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc1.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc1.SupportPackageIsVersion4

// Client API for Todo service

type TodoClient interface {
	List(ctx context.Context, in *Void, opts ...grpc1.CallOption) (*TaskList, error)
	Add(ctx context.Context, in *Task, opts ...grpc1.CallOption) (*Void, error)
}

type todoClient struct {
	cc *grpc1.ClientConn
}

func NewTodoClient(cc *grpc1.ClientConn) TodoClient {
	return &todoClient{cc}
}

func (c *todoClient) List(ctx context.Context, in *Void, opts ...grpc1.CallOption) (*TaskList, error) {
	out := new(TaskList)
	err := grpc1.Invoke(ctx, "/grpc.Todo/List", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *todoClient) Add(ctx context.Context, in *Task, opts ...grpc1.CallOption) (*Void, error) {
	out := new(Void)
	err := grpc1.Invoke(ctx, "/grpc.Todo/Add", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Todo service

type TodoServer interface {
	List(context.Context, *Void) (*TaskList, error)
	Add(context.Context, *Task) (*Void, error)
}

func RegisterTodoServer(s *grpc1.Server, srv TodoServer) {
	s.RegisterService(&_Todo_serviceDesc, srv)
}

func _Todo_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc1.UnaryServerInterceptor) (interface{}, error) {
	in := new(Void)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TodoServer).List(ctx, in)
	}
	info := &grpc1.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.Todo/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TodoServer).List(ctx, req.(*Void))
	}
	return interceptor(ctx, in, info, handler)
}

func _Todo_Add_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc1.UnaryServerInterceptor) (interface{}, error) {
	in := new(Task)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TodoServer).Add(ctx, in)
	}
	info := &grpc1.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.Todo/Add",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TodoServer).Add(ctx, req.(*Task))
	}
	return interceptor(ctx, in, info, handler)
}

var _Todo_serviceDesc = grpc1.ServiceDesc{
	ServiceName: "grpc.Todo",
	HandlerType: (*TodoServer)(nil),
	Methods: []grpc1.MethodDesc{
		{
			MethodName: "List",
			Handler:    _Todo_List_Handler,
		},
		{
			MethodName: "Add",
			Handler:    _Todo_Add_Handler,
		},
	},
	Streams:  []grpc1.StreamDesc{},
	Metadata: "grpc.proto",
}

// Client API for Greeter service

type GreeterClient interface {
	SayHello(ctx context.Context, in *HelloRequest, opts ...grpc1.CallOption) (*HelloReply, error)
}

type greeterClient struct {
	cc *grpc1.ClientConn
}

func NewGreeterClient(cc *grpc1.ClientConn) GreeterClient {
	return &greeterClient{cc}
}

func (c *greeterClient) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc1.CallOption) (*HelloReply, error) {
	out := new(HelloReply)
	err := grpc1.Invoke(ctx, "/grpc.Greeter/SayHello", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Greeter service

type GreeterServer interface {
	SayHello(context.Context, *HelloRequest) (*HelloReply, error)
}

func RegisterGreeterServer(s *grpc1.Server, srv GreeterServer) {
	s.RegisterService(&_Greeter_serviceDesc, srv)
}

func _Greeter_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc1.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).SayHello(ctx, in)
	}
	info := &grpc1.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.Greeter/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).SayHello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Greeter_serviceDesc = grpc1.ServiceDesc{
	ServiceName: "grpc.Greeter",
	HandlerType: (*GreeterServer)(nil),
	Methods: []grpc1.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _Greeter_SayHello_Handler,
		},
	},
	Streams:  []grpc1.StreamDesc{},
	Metadata: "grpc.proto",
}

func init() { proto.RegisterFile("grpc.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 242 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x90, 0x31, 0x4f, 0xc3, 0x30,
	0x10, 0x85, 0x1b, 0x6a, 0xda, 0xf0, 0x40, 0x08, 0xdd, 0x14, 0x65, 0x21, 0x3a, 0x21, 0x94, 0x01,
	0x65, 0x08, 0x33, 0x03, 0x13, 0x0c, 0xb0, 0x84, 0x8a, 0xdd, 0xe0, 0x53, 0x55, 0x35, 0xad, 0x43,
	0x6c, 0x24, 0xf2, 0xef, 0x91, 0xdd, 0x46, 0x84, 0xed, 0xf9, 0xde, 0xf3, 0xbd, 0x4f, 0x07, 0xac,
	0xfb, 0xee, 0xb3, 0xea, 0x7a, 0xeb, 0x2d, 0xa9, 0xa0, 0xb9, 0x82, 0x5a, 0x69, 0xb7, 0x25, 0x82,
	0xf2, 0xf2, 0xe3, 0xb3, 0xa4, 0x48, 0xca, 0xb3, 0x26, 0xea, 0x30, 0x33, 0x76, 0x2f, 0xd9, 0x49,
	0x91, 0x94, 0x69, 0x13, 0x35, 0xdf, 0x21, 0x0d, 0xf9, 0x97, 0x8d, 0xf3, 0x54, 0xe0, 0xd4, 0x6b,
	0xb7, 0x75, 0x59, 0x52, 0xcc, 0xcb, 0xf3, 0x1a, 0x55, 0xdc, 0x1e, 0xec, 0xe6, 0x60, 0xf0, 0x02,
	0xea, 0xdd, 0x6e, 0x0c, 0x33, 0x2e, 0x9e, 0xa5, 0x6d, 0x6d, 0x23, 0x5f, 0xdf, 0xe2, 0xe2, 0xe6,
	0xbd, 0xde, 0xc9, 0xd8, 0x16, 0x34, 0xdf, 0x02, 0xc7, 0x4c, 0xd7, 0x0e, 0x94, 0x61, 0xb9, 0x13,
	0xe7, 0xf4, 0x7a, 0x0c, 0x8d, 0xcf, 0xfa, 0x15, 0x6a, 0x65, 0x8d, 0xa5, 0x1b, 0xa8, 0x48, 0x71,
	0xac, 0x0d, 0x3d, 0xf9, 0xe5, 0x1f, 0x42, 0xf0, 0x78, 0x46, 0xd7, 0x98, 0x3f, 0x1a, 0x43, 0x13,
	0xb6, 0x7c, 0xf2, 0x81, 0x67, 0xf5, 0x03, 0x96, 0x4f, 0xbd, 0x88, 0x97, 0x9e, 0x6a, 0xa4, 0x6f,
	0x7a, 0x88, 0x10, 0x44, 0x87, 0xd0, 0x94, 0x3a, 0xbf, 0xfa, 0x37, 0xeb, 0xda, 0x81, 0x67, 0x1f,
	0x8b, 0x78, 0xcc, 0xfb, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xef, 0x57, 0x7e, 0x40, 0x5a, 0x01,
	0x00, 0x00,
}
